# Generated by Django 5.2.4 on 2025-07-13 23:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('livestockregistry', '0002_profile_livestock_image_property_latitude_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='direccion',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='telefono',
            new_name='phone',
        ),
    ]
