# Generated by Django 5.2.4 on 2025-07-16 10:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livestockregistry', '0003_rename_direccion_profile_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='parentchild',
            name='insemination_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='parentchild',
            name='is_by_insemination',
            field=models.BooleanField(default=False, help_text='Marcar si fue producto de inseminación'),
        ),
        migrations.AlterField(
            model_name='parentchild',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parent_relations', to='livestockregistry.livestock'),
        ),
    ]
